export const LanguageConstant = {
  en: {

    "HOMEPAGE": "Homepage",
    "ADMIN_SYSTEM": "Administration system",

    "ADD": "Add",
    "EDIT": "Edit",
    "DELETE": "Delete",
    "CONFIRM": "Confirm",
    "CANCEL": "Cancel",
    "SAVE": "Save",

    "EDIT_TITLE": "Edit Form ",
    "ADD_TITLE": "Create Form ",

    "ERR_SYSTEM": "Something went wrong.",
    "ERR_CONNECT_SERVER": "Unable to connect to server!",
    "ACCOUNT_WITHOUT_PRIVILEDGE": "You do not have access right",

    "MSG_UPDATE_DONE": "Updated successfully!",
    "MSG_CREATE_DONE": "Created successfully!",
    "MSG_CHANGE_DONE": "Changed successfully!",
    "CONFIRM_DELETE": "Are you sure to DELETE this record?",
    "CONFIRM_CHANGE_STATUS": "Are you sure to CHANGE STATUS this record?",
    "CAN_NOT_BE_EMPTY": "This field can not be empty!",

    "BACHELOR": "Bachelor",
    "MASTER": "Master",
    "DOCTORAL": "Doctoral",

    "USER_INFO": "User Information",

    "USER_NAME": "Username",
    "USER_NAME_TIP": "Your Username/Email",
    "USER_NAME_ERR": "Username can not be empty!",

    "PASSWORD": "Password",
    "PASSWORD_TIP": "Your Password",
    "PASSWORD_ERR": "Password can not be empty!",

    "REMEMBER_ME": "Remember me",
    "FORGOR": "Forgot your password?",
    "LOG_IN": "Log In",
    "LOG_IN_BODY": "Sign In to your account",
    "LOG_IN_GOOGLE": "Log In with Google",
    "SIGN_UP": "Sign Up",
    "LOG_OUT": "Log Out",
    "WELCOME_MSG": "Welcome back!",

    "OR": "Or",

    "NO": "No",
    "STATUS": "Status",
    "ACTIVE": "Active",
    "INACTIVE": "Inactive",
    "ACTIONS": "Actions",

    "NUMBER_LIST": "Number of item(s)",
    "PAGE": "page",
    "TOTAL": "Total",
    "ITEM": "item(s)",

    "FACULTY_NAME": "Faculty Name",
    "FACULTY_NAME_EN": "Faculty English Name",
    "FACULTY_NAME_LV": "Faculty Latvian Name",
    "CHOOSE_FACULTY": "Choose faculty...",

    "PROGRAM_NAME": "Program Name",
    "STUDY_LEVEL": "Study Level",
    "PROGRAM_NAME_EN": "Program English Name",
    "PROGRAM_NAME_LV": "Program Latvian Name",
    "CHOOSE_STUDY_LEVEL": "Choose study level...",
    "CHOOSE_PROGRAM": "Choose program...",

    "INDUSTRY_NAME": "Industry List",
    "INDUSTRY_NAME_EN": "Industry English Name",
    "INDUSTRY_NAME_LV": "Industry Latvian Name",
    "CHOOSE_INDUSTRY": "Choose industry, mulitple allowed...",

    "POST_TYPE_NAME": "Post Type",
    "POST_TYPE_NAME_EN": "Post Type in English",
    "POST_TYPE_NAME_LV": "Post Type in Latvian",

    "SEARCH_BTN": "Search",
    "SEARCH": "Search...",
    "CATEGORIES": "Categories",
    "ANNOUNCEMENT": "Announcements",
    "THESIS_TOPIC": "Thesis Topics",
    "JOB_TOPIC": "Job Offers",
    "CORE": "Core",
    "FUNCTIONS": "Functions",

    "MORE": "View more",

    "CONTACT_US": "Contact us",
    "ABOUT_US": "About us",

    "STUDENT": "Student",
    "UNIVERSITY": "University",
    "COMPANY": "Company",
    "ADMIN": "Administrator",

    "INFO_1": "University Management System",
    "INFO_2": "Master Thesis",
    "INFO_3": "Under Development",

    "ADDRESS_1": "Address line 1",
    "ADDRESS_2": "Address line 2",
    "ADDRESS_3": "Address line 3",

    "PHONE_NUM": "(+371) 2345 6789",
    "EMAIL": "contact@lunih.lv",
    "DESIGN_COST": "Developed by lunih - Liepaja University",

    "DASHBOARD": "Dashboard",
    "FACULTY": "Faculty",
    "PROGRAM": "Program",
    "INDUSTRY": "Industry",
    "POST_TYPE": "Post Type",
    "USER_ACCOUNT": "Users & Account",
    "POST_MANAGEMENT": "Post Management",
    "POST": "Post",
    "APPROVE_STUDENT": "Approve Student",
    "ADDRESS": "Address",
    "PHONE_NUMBER": "Phone number",

    "ACCOUNT_EMAIL": "Email",
    "ACCOUNT_PASSWORD": "Password",
    "GENDER": "Gender",
    "CHOOSE_GENDER": "(Optional) Select gender...",
    "MALE": "Male",
    "FEMALE": "Female",
    "OTHER": "Other",
    "MR": "Mr.",
    "MRS": "Mrs.",
    "MS": "Ms.",

    "STUDENT_ID": "Student ID",
    "STUDENT_FIRST_NAME": "Name",
    "STUDENT_SUR_NAME": "Surname",
    "BIRTHDAY": "Birthday",
    "CHOOSE_BIRTHDAY": "(Optional) Select date...",

    "UNIVERSITY_NAME": "Fullname",

    "COMPANY_NAME": "Company Name",
    "COMPANY_TYPE": "Company Type",
    "COMPANY_CONTACT_PERSON_NAME": "Person name",
    "COMPANY_DESCRIPTION": "Company Description",
    "COMPANY_PRIVATE": "Private",
    "COMPANY_PUBLIC": "Public",
    "COMPANY_NGO": "NGO",
    "COMPANY_GOVERNMENT": "Government",
    "COMPANY_EDUCATIONAL": "Educational",
    "COMPANY_OTHER": "Other",
    "COMPANY_ADDRESS": "Company Address",
    "COMPANY_WEBSITE": "Company Website",
    "COMPANY_CONTACT_PERSON_TITLE": "Person Title",
    "COMPANY_CONTACT_PERSON_EMAIL": "Person Email",
    "COMPANY_CONTACT_PERSON_DEPARTMENT": "Person Department",
    "COMPANY_CONTACT_PERSON_PHONE": "Person Phonenumber",

    "POST_TITLE_EN": "Post title in English",
    "POST_TITLE_LV": "Post title in Latvian",
    "POST_DESCRIPTION_EN": "Post description in English",
    "POST_DESCRIPTION_LV": "Post description in Latvian",
    "POST_NUM_SLOT": "Number of slots",
    "POST_START_END_DATE": "Post start & end date",
    "POST_START_DATE": "Start date",
    "POST_END_DATE": "End date",
    "POST_STUDENT_LIST": "Student applied list",
    "POST_QUEUE_LIST": "Student queue list",

    "POST_TITLE": "Post title",
    "NUM_SLOT": "Slots"
  },

  lv: {
    "HOMEPAGE": "Sākums",
    "ADMIN_SYSTEM": "Administrācija",

    "ADD": "Pievienot",
    "EDIT": "Labot",
    "DELETE": "Dzēst",
    "CONFIRM": "Apstiprināt",
    "CANCEL": "Atcelt",
    "SAVE": "Saglabāt",

    "EDIT_TITLE": "Labot formu ",
    "ADD_TITLE": "Izveidot formu",

    "ERR_SYSTEM": "Kaut kas nogāja greizi",
    "ERR_CONNECT_SERVER": "Nav iespējams sazināties ar serveri!",
    "ACCOUNT_WITHOUT_PRIVILEDGE": "Jums nav piekļuves tiesības!",

    "MSG_UPDATE_DONE": "Informācija atjaunota!",
    "MSG_CREATE_DONE": "Veiksmīgi izveidots!",
    "MSG_CHANGE_DONE": "Informācija atjaunota!",
    "CONFIRM_DELETE": "Vai tiešām vēlies dzēst šo ierakstu?",
    "CONFIRM_CHANGE_STATUS": "Vai tiešām vēlies mainīt statusu šim ierakstam?",
    "CAN_NOT_BE_EMPTY": "Šī sadaļa nevar būt tukša!",

    "BACHELOR": "Bakalaurs",
    "MASTER": "Maģistrantūra",
    "DOCTORAL": "Doktorantūra",

    "USER_INFO": "Lietotāja informācija",

    "USER_NAME": "Lietotājvārds",
    "USER_NAME_TIP": "Lietotājvārds/E-pasts",
    "USER_NAME_ERR": "Lietotājvārds nevar būt tukšs!",

    "PASSWORD": "Parole",
    "PASSWORD_TIP": "Tava parole",
    "PASSWORD_ERR": "Parole nevar būt tukša",

    "REMEMBER_ME": "Atcerēties mani",
    "FORGOR": "Aizmirsi paroli?",
    "LOG_IN": "Pierakstīties",
    "LOG_IN_BODY": "Pierakstieties savā kontā",
    "LOG_IN_GOOGLE": "Log In with Google",
    "SIGN_UP": "Reģistrēties",
    "LOG_OUT": "Izrakstīties",
    "WELCOME_MSG": "Laipni lūdzam atpakaļ!",

    "OR": "Vai",
    "NO": "Nr.",
    "STATUS": "Statuss",
    "ACTIVE": "Aktīvs",
    "INACTIVE": "Neaktīvs",
    "ACTIONS": "Darbības",

    "NUMBER_LIST": "Vienību skaits",
    "PAGE": "lapa",
    "TOTAL": "Kopā",
    "ITEM": "vienības",

    "FACULTY_NAME": "Fakultātes nosaukums",
    "FACULTY_NAME_EN": "Fakultātes nosaukums EN",
    "FACULTY_NAME_LV": "Fakultātes nosaukums LV",

    "PROGRAM_NAME": "Programmas nosaukums",
    "STUDY_LEVEL": "Studiju līmenis",
    "PROGRAM_NAME_EN": "Programmas nosaukums EN",
    "PROGRAM_NAME_LV": "Programmas nosaukums LV",
    "CHOOSE_STUDY_LEVEL": "Izvēlies studiju līmeni...",
    "CHOOSE_PROGRAM": "Izvēlies programmu...",
    "CHOOSE_FACULTY": "izvēlēties fakultāti...",

    "INDUSTRY_NAME": "Industrijas nosaukums",
    "INDUSTRY_NAME_EN": "Industrijas nosaukums EN",
    "INDUSTRY_NAME_LV": "Industrijas nosaukums LV",
    "CHOOSE_INDUSTRY": "Izvēlies industriju, iespējami vairāki varianti...",

    "POST_TYPE_NAME": "Ieraksts veids",
    "POST_TYPE_NAME_EN": "Ieraksta veids EN",
    "POST_TYPE_NAME_LV": "Ieraksta veids LV",

    "SEARCH_BTN": "Meklēt",
    "SEARCH": "Meklē...",
    "CATEGORIES": "Kategorijas",
    "ANNOUNCEMENT": "Paziņojums",
    "THESIS_TOPIC": "Ideju tēmas",
    "JOB_TOPIC": "Darba piedāvājumi",
    "MORE": "Apskatīt vēl",
    "CORE": "Core",
    "FUNCTIONS": "Funkcijas",

    "CONTACT_US": "Sazināties ar mums",
    "ABOUT_US": "Par mums",

    "STUDENT": "Students",
    "UNIVERSITY": "Universitāte",
    "COMPANY": "Kompānija",
    "ADMIN": "Administrators",

    "INFO_1": "University Management System",
    "INFO_2": "Master Thesis",
    "INFO_3": "Under Development",

    "ADDRESS_1": "Address line 1",
    "ADDRESS_2": "Address line 2",
    "ADDRESS_3": "Address line 3",

    "PHONE_NUM": "(+371) 2345 6789",
    "EMAIL": "contact@lunih.lv",
    "DESIGN_COST": "Developed by lunih - Liepaja University",

    "DASHBOARD": "Dashboard",
    "FACULTY": "Fakultāte",
    "PROGRAM": "Programma",
    "INDUSTRY": "Industrija",
    "POST_TYPE": "Ierakstu veds",
    "USER_ACCOUNT": "Lietotājs & Konts",
    "POST_MANAGEMENT": "Publikācijas menedžments",
    "POST": "Publikācija",
    "APPROVE_STUDENT": "Apstiprināt studentu",
    "ADDRESS": "Address lv",
    "PHONE_NUMBER": "Telefona numurs",

    "ACCOUNT_EMAIL": "E-pasts",
    "ACCOUNT_PASSWORD": "Parole",
    "GENDER": "Dzimums",
    "CHOOSE_GENDER": "Izvēlies dzimumu...",
    "MALE": "Vīriešu",
    "FEMALE": "Sieviešu",
    "OTHER": "Cits",
    "MR": "Mr.",
    "MRS": "Mrs.",
    "MS": "Ms.",

    "STUDENT_ID": "Studenta ID",
    "STUDENT_FIRST_NAME": "Vārds",
    "STUDENT_SUR_NAME": "Uzvārds",
    "BIRTHDAY": "Dzimšanas diena",
    "CHOOSE_BIRTHDAY": "Izvēlies datumu...",

    "UNIVERSITY_NAME": "Pilns vārds",

    "COMPANY_NAME": "Kompānijas nosaukums",
    "COMPANY_TYPE": "Kompānijas veids",
    "COMPANY_CONTACT_PERSON_NAME": "Kontaktpersonas vārds",
    "COMPANY_DESCRIPTION": "Kompānijas apraksts",
    "COMPANY_PRIVATE": "Privāra",
    "COMPANY_PUBLIC": "Publiska",
    "COMPANY_NGO": "Nevalstiskā organizācija",
    "COMPANY_GOVERNMENT": "Valsts vai pašvaldības iestāde",
    "COMPANY_EDUCATIONAL": "Izglītības iestāde",
    "COMPANY_OTHER": "Cits",
    "COMPANY_ADDRESS": "Kompānijas adrese",
    "COMPANY_WEBSITE": "Kompānijas mājaslapa",
    "COMPANY_CONTACT_PERSON_TITLE": "Kontaktpersonas amats",
    "COMPANY_CONTACT_PERSON_EMAIL": "Kontaktpersonas e-pasts",
    "COMPANY_CONTACT_PERSON_DEPARTMENT": "Person Department lv",
    "COMPANY_CONTACT_PERSON_PHONE": "Kontaktpersonas telefona numurs",

    "POST_TITLE_EN": "Idejas tēma EN",
    "POST_TITLE_LV": "Idejas tēma LV",
    "POST_DESCRIPTION_EN": "Idejas apraksts angļu valodā",
    "POST_DESCRIPTION_LV": "Idejas apraksts latviešu valodā",
    "POST_NUM_SLOT": "Dalībnieku skaits",
    "POST_START_END_DATE": "Ieraksta izpildes laiks sākums & beigu datums",
    "POST_START_DATE": "Sākuma datums",
    "POST_END_DATE": "Beigu datums",
    "POST_STUDENT_LIST": "Studentu pieteikumu saraksts",
    "POST_QUEUE_LIST": "Studentu rindas saraksts",

    "POST_TITLE": "Idejas tēma",
    "NUM_SLOT": "Dalībnieku"
  }
};